sonar.projectKey=soubruno_hackathon-starter-devops
sonar.organization=soubruno

# Informações do Projeto
sonar.projectName=hackathon-starter-devops
sonar.projectVersion=1.0.0

# Código-fonte e testes
sonar.sources=controllers,models,app.js
sonar.tests=test
sonar.test.inclusions=test/**/*.test.js

# Exclusões
sonar.exclusions=**/node_modules/**,public/**,tmp/**
sonar.sourceEncoding=UTF-8